# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/java-tron
    steps:
    - checkout
    - run: sudo sh tron.sh
    - run: ./gradlew build
    - run: ./gradlew jacocoTestReport
    - run: sudo bash deploy.sh

